addSbtPlugin("com.eed3si9n"     % "sbt-assembly"        % "0.14.10")
addSbtPlugin("com.mintbeans"    % "sbt-ecr"             % "0.15.0")
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.5.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.5.0")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"        % "2.2.1")
